## Step 1: Build the Angular app
#FROM node:20 AS build
#
#WORKDIR /app
#
## Copy the package.json and package-lock.json files
#COPY package.json package-lock.json ./
#
## Install global dependencies, including the Nx CLI
#RUN npm install -g nx
#
## Install dependencies
#RUN npm install --force
#
## Copy the rest of the Angular project
#COPY . .
#
## Build the Angular app
#RUN npm run build rule-creator-app --prod --verbose
#
## Step 2: Serve the app using nginx
#FROM nginx:alpine
#
## Copy the build artifacts from the build stage
#COPY --from=build /app/dist/apps/rule-creator-app /usr/share/nginx/html
#
## Expose port 80 for the app
#EXPOSE 80
#
## Start nginx
#CMD ["nginx", "-g", "daemon off;"]
